default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: intime

development:
  <<: *default
  database: intime

test:
  <<: *default
  database: intime_test

staging:
  <<: *default
  database: intime
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  database: intime
  password: <%= ENV['DB_PASSWORD'] %>
